LOG_LEVEL = "ERROR"
DJANGO_DEBUG = True
AUTO_LOGOUT_ENABLED = False
AUTHENTICATION_ACTIONS = ["authenticate"]
TEST_ENTRY_ACTIONS = ["combined_board_test", "paper_test"]
UNIVERSAL_ACTIONS = ["plants", "vendors", "customers", "corrugators", "paper_types", "grades", "flutes",
                     "order_test_codes"]
PROGRESS_ACTIONS = ["search_order", "find_rolls"] + ["find_" + action for action in UNIVERSAL_ACTIONS]
MYSQL_ACTIONS = ["accounts", "lithos", "paper_test_reasons", "paper_test_positions", "paper_test_types",
                 "combined_board_test_reasons", "combined_board_test_layers", "combined_board_test_types",
                 "special_instruction_codes"] + UNIVERSAL_ACTIONS + TEST_ENTRY_ACTIONS
ALL_PLANTS_DICTIONARY = {"cc": "Cincinnati", "sp": "Concord", "da": "Dallas", "mc": "Louisville", "ms": "Mason", "op": "Massillon",
                         "gc": "Massillon - Coating", "pa": "Palmyra"}
IS_DB_LIVE = True
# Note - Used in rare spots, might not be updated
DEFAULT_PREFERENCES = {"landing_page": "dashboard",
                       "page_settings": {"dashboard": {"show_3d_graphs": False},
                                         "paper_tests": {
                                             "filter_attributes": ["Start Date", "End Date", "Roll/Litho #", "Author",
                                                                   "Plant",
                                                                   "Grade", "Type"],
                                             "olv_columns": ["ID", "Created", "Roll/Litho #", "Roll Grade/Litho Point", "Roll Type", "Roll Width",
                                                             "Test Type", "Test Value"]},
                                         "paper_test_entry": {"test_entry_count": 2,
                                                              "roll_view_columns": ["Roll #", "Grade",
                                                                                    "Type", "Width",
                                                                                    "Received"],
                                                              "litho_paper_view_columns": ["Litho UUID", "Litho Point",
                                                                                    "Created At", "Plant Code"],
                                                              "test_view_columns": ["Roll #",
                                                                                    "Test Type",
                                                                                    "Test Reason",
                                                                                    "Test Position",
                                                                                    "Test Value"],
                                                              "litho_paper_test_view_columns": ["Litho UUID",
                                                                                                "Litho Point",
                                                                                                "Test Type",
                                                                                                "Test Reason",
                                                                                                "Test Value",
                                                                                                "Plant Code"],
                                                              "default_paper_test_types": [""],
                                                              "selected_roll_attrs": ["Roll Number",
                                                                                      "Vendor Number",
                                                                                      "Vendor Name",
                                                                                      "Grade", "Type",
                                                                                      "Width",
                                                                                      "Received Date",
                                                                                      "Talley ID",
                                                                                      "Vendor Code",
                                                                                      "Original Weight",
                                                                                      "Original Lineal FT",
                                                                                      "Original MSF",
                                                                                      "Mill", "Moisture",
                                                                                      "Plant"],
                                                              "selected_litho_attrs": ["Litho UUID", "Litho Point", "Created At", "Plant Code"],
                                                              },
                       "combined_tests": {
                           "filter_attributes": ["Start Date", "End Date", "Order #",
                                                 "Author", "Plant", "Flute", "Test"],
                           "olv_columns": ["Order #", "Created", "Plant", "Test", "Flute",
                                                             "Author", "Test Type", "Test Reason",
                                                             "Test Value"]},
                                         "combined_test_entry": {"test_entry_count": 2, "layer_count": 2,
                                                                 "order_view_cols": ["Order No",
                                                                                     "Customer Name",
                                                                                     "Quantity", "Width",
                                                                                     "Length",
                                                                                     "Plant Code"],
                                                                 "test_view_cols": ["Order #",
                                                                                    "Test Type",
                                                                                    "Test Reason",
                                                                                    "Test Value"],
                                                                 "default_combined_test_types": [""],
                                                                 "selected_order_attrs": ["Order Number",
                                                                                          "Plant Code",
                                                                                          "Customer Name",
                                                                                          "Customer Number",
                                                                                          "Ship To",
                                                                                          "Order Date",
                                                                                          "Test",
                                                                                          "Corrugator ID",
                                                                                          "Corrugator Name",
                                                                                          "Ship Date",
                                                                                          "Customer PO",
                                                                                          "Spec Code",
                                                                                          "Flute Code",
                                                                                          "Flute Description",
                                                                                          "Length",
                                                                                          "Width",
                                                                                          "Quantity",
                                                                                          "Walls"]}}}
