# Generated by Django 4.2.13 on 2024-10-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='vroll_no',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
