# Generated by Django 4.2.13 on 2024-10-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_roll_vroll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cust_po',
            field=models.CharField(max_length=64),
        ),
    ]
