# Generated by Django 4.2.13 on 2024-10-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_cust_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='tally_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
