# Generated by Django 4.2.13 on 2024-10-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_roll_tally_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='combinedboardtestlayer',
            constraint=models.UniqueConstraint(fields=('code', 'plant'), name='unique_code_plant_combined_board_test_layer'),
        ),
        migrations.AddConstraint(
            model_name='combinedboardtestreason',
            constraint=models.UniqueConstraint(fields=('code', 'plant'), name='unique_code_plant_combined_board_test_reason'),
        ),
        migrations.AddConstraint(
            model_name='combinedboardtesttype',
            constraint=models.UniqueConstraint(fields=('code', 'plant'), name='unique_code_plant_combined_board_test_type'),
        ),
        migrations.AddConstraint(
            model_name='corrugator',
            constraint=models.UniqueConstraint(fields=('code', 'plant'), name='unique_code_plant_corrugator'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('code', 'plant'), name='unique_code_plant_customer'),
        ),
        migrations.AddConstraint(
            model_name='flute',
            constraint=models.UniqueConstraint(fields=('code', 'plant'), name='unique_code_plant_flute'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('code', 'plant'), name='unique_code_plant_grade'),
        ),
        migrations.AddConstraint(
            model_name='litho',
            constraint=models.UniqueConstraint(fields=('code', 'plant'), name='unique_code_plant_litho'),
        ),
        migrations.AddConstraint(
            model_name='ordertestcode',
            constraint=models.UniqueConstraint(fields=('code', 'plant'), name='unique_code_plant_order_test_code'),
        ),
        migrations.AddConstraint(
            model_name='papertestposition',
            constraint=models.UniqueConstraint(fields=('code', 'plant'), name='unique_code_plant_paper_test_position'),
        ),
        migrations.AddConstraint(
            model_name='papertestreason',
            constraint=models.UniqueConstraint(fields=('code', 'plant'), name='unique_code_plant_paper_test_reason'),
        ),
        migrations.AddConstraint(
            model_name='papertesttype',
            constraint=models.UniqueConstraint(fields=('code', 'plant'), name='unique_code_plant_paper_test_type'),
        ),
        migrations.AddConstraint(
            model_name='papertype',
            constraint=models.UniqueConstraint(fields=('code', 'plant'), name='unique_code_plant_paper_type'),
        ),
        migrations.AddConstraint(
            model_name='specialinstructioncode',
            constraint=models.UniqueConstraint(fields=('code', 'plant'), name='unique_code_plant_special_instruction_code'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('code', 'plant'), name='unique_code_plant_vendor'),
        ),
    ]
