# Generated by Django 4.2.13 on 2025-02-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lithopaper_papertest_litho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lithopaper',
            name='litho',
        ),
        migrations.AddField(
            model_name='lithopaper',
            name='litho_pt',
            field=models.IntegerField(default=0),
        ),
    ]
